baseURL = 'https://sebastianmarines.github.io/'
languageCode = 'en-us'
title = 'Sebastian Marines'
theme = 'holy'

[menu]

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 10
